services:
  - type: web
    name: heart-disease-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "8080"
